Algoritmo "Soma_10"

// Descrição   : Este programa o programa lê e soma números 10 números que o usuário digitou.
// Autor(a)    : Nicolas Costa Ribeiro
// Data atual  : 20/08/2021
Var
resp, num, cont: inteiro

Inicio

//REPETIÇÃO
para cont de 1 ate 10 faca
     escreval("Digite um número inteiro:")
     leia(num)
     resp <- resp + num
     limpatela
     escreval("O valor da soma de todos números digitados é", resp)

fimpara

Fimalgoritmo